# Generated by Django 4.1.3 on 2022-11-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200205_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='immagine',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
