# Generated by Django 4.1.3 on 2022-11-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_item_immagine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Classica'), ('SP', 'Prestige'), ('OW', 'Out Wear')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('N', 'Classica'), ('BS', 'Prestige')], max_length=2),
        ),
    ]
